// Generated by gencpp from file ros_myo/MyoPose.msg
// DO NOT EDIT!


#ifndef ROS_MYO_MESSAGE_MYOPOSE_H
#define ROS_MYO_MESSAGE_MYOPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_myo
{
template <class ContainerAllocator>
struct MyoPose_
{
  typedef MyoPose_<ContainerAllocator> Type;

  MyoPose_()
    : pose(0)  {
    }
  MyoPose_(const ContainerAllocator& _alloc)
    : pose(0)  {
  (void)_alloc;
    }



   typedef uint8_t _pose_type;
  _pose_type pose;


    enum { REST = 1u };
     enum { FIST = 2u };
     enum { WAVE_IN = 3u };
     enum { WAVE_OUT = 4u };
     enum { FINGERS_SPREAD = 5u };
     enum { THUMB_TO_PINKY = 6u };
     enum { UNKNOWN = 0u };
 

  typedef boost::shared_ptr< ::ros_myo::MyoPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_myo::MyoPose_<ContainerAllocator> const> ConstPtr;

}; // struct MyoPose_

typedef ::ros_myo::MyoPose_<std::allocator<void> > MyoPose;

typedef boost::shared_ptr< ::ros_myo::MyoPose > MyoPosePtr;
typedef boost::shared_ptr< ::ros_myo::MyoPose const> MyoPoseConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_myo::MyoPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_myo::MyoPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_myo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_myo': ['/home/feraldo/ROS_ws/bionic_hand_ws/src/ros_myo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_myo::MyoPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_myo::MyoPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_myo::MyoPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_myo::MyoPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_myo::MyoPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_myo::MyoPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_myo::MyoPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "056fd823a1b40e3fef451ecc8dcf5690";
  }

  static const char* value(const ::ros_myo::MyoPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x056fd823a1b40e3fULL;
  static const uint64_t static_value2 = 0xef451ecc8dcf5690ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_myo::MyoPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_myo/MyoPose";
  }

  static const char* value(const ::ros_myo::MyoPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_myo::MyoPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Pose message\n\
uint8 REST = 1\n\
uint8 FIST = 2\n\
uint8 WAVE_IN = 3\n\
uint8 WAVE_OUT = 4\n\
uint8 FINGERS_SPREAD = 5\n\
uint8 THUMB_TO_PINKY = 6\n\
uint8 UNKNOWN = 0\n\
uint8 pose\n\
";
  }

  static const char* value(const ::ros_myo::MyoPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_myo::MyoPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MyoPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_myo::MyoPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_myo::MyoPose_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MYO_MESSAGE_MYOPOSE_H
